services:
  - type: web
    name: pdf-compressor
    env: node
    buildCommand: apt-get install -y ghostscript && npm install
    startCommand: npm start
    plan: free
    healthCheckPath: /api/health
